server:
  port: 8061

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderService
    username: root
    password: root
  jpa:
    hibernate:
      auto-ddl: none
    show-sql: true
  security:
    user:
      name: akhil
      password: akhil

inventory:
  api-gateway:
    url: http://localhost:8000
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
  show-actuator: true
