server:
  port: 8061

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderService
    username: root
    password: root
  jpa:
    hibernate:
      auto-ddl: none
    show-sql: true
  security:
    user:
      name: akhil
      password: akhil

inventory:
  api-gateway:
    url: http://localhost:8000
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
  show-actuator: true


management:
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  health:
    circuitbreakers:
      enabled: true
    defaults:
      show-details: always
    db:
      enabled: true
    disk-space:
      enabled: true
    ping:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      inventory:
        timeout-duration: 3s
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 2s
