server:
  port: 8062

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventoryService
    username: root
    password: root
  jpa:
    hibernate:
      auto-ddl: none
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
  show-actuator: true

